apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-ticket
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - nacos.yaml
  - sentinel-dashboard.yaml
  - ai-service.yaml
  - platform-service.yaml
  - gateway.yaml
  - frontend.yaml
  - ingress.yaml
